theme             : cayman
title             : Food order application homepage
description       : Bookmark this to keep an eye on my project updates!
source            : .
destination       : ./public