theme       : cayman
title       : Food order application homepage
description : Bookmark this to keep an eye on my project updates!
source      : .
destination : ./public
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme